apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: app1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: docker.io/zimnydocker/jaeger-cloud-run:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000