receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - http://*
        - https://*

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
    
processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]

extensions:
  health_check: