receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*
            - "*"

exporters:
  otlp:
    endpoint: "jaeger-service.otlp-blueprint.local:4317"
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

extensions:
  health_check:
