receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318      
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
    
processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]

extensions:
  health_check: