receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - https://34.111.15.51.nip.io/
exporters:
  jaeger:
    endpoint: "simplest-collector.default.svc.cluster.local:14250"
    tls:
      insecure: true


processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
extensions:
  health_check:
