receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  jaeger:
    endpoint: http://dev-otlp-lb-1255345766.us-east-1.elb.amazonaws.com:8082
    tls:
      insecure: true
processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]

extensions:
  health_check:
