version: '3.9'
services:
  postgresql:
    container_name: oltp_db
    image: postgres:14.2-alpine
    hostname: postgresql.otlp-blueprint.local
    environment:
      - POSTGRES_USER=otlpuser
      - POSTGRES_PASSWORD=otlppassword
      - POSTGRES_DB=tododb
    networks:
      - otlp-network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgresql/data:/var/lib/postgresql/data
    #   - ./postgresql/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  backend:
    container_name: backend
    hostname: backend.otlp-blueprint.local
    build:
      context: ./
      dockerfile: Backend.dockerfile
      target: source
    # env_file:
    #   - ./pkg-svcs/backend/.env
    environment:
      - APP_VERSION=1.0.0
    ports:
      - "3000:3000"
    networks:
      - otlp-network
    depends_on:
      - postgresql
      - jaeger
    volumes:
      - ./pkg-svcs/backend:/app/backend
    command: "npm run start:container"
  
  frontend:
    container_name: frontend
    hostname: frontend.otlp-blueprint.local
    build:
      context: ./
      dockerfile: Frontend.dockerfile
      target: source
    # env_file:
    #   - ./pkg-svcs/frontend/.env
    ports:
      - "8080:8080"
    networks:
      - otlp-network
    depends_on:
      - backend
      - postgresql
      - jaeger
    volumes:
      - ./pkg-svcs/frontend:/app/frontend
    command: "npm run start:container"

  jaeger:
    image: jaegertracing/all-in-one:1.38.1
    hostname: jaeger-service.otlp-blueprint.local
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16685:16685"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - otlp-network
  
  collector:
    image: otel/opentelemetry-collector:0.56.0
    hostname: collector.otlp-blueprint.local
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - otlp-network

  grafana:
    image: grafana/grafana:9.3.2
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3030:3000"
    networks:
      - otlp-network

volumes:
  postgresql:
    external: false
networks:
      otlp-network:
