version: '3.9'
services:
  postgresql:
    container_name: oltp_db
    image: postgres:10.16-alpine
    environment:
      - POSTGRES_USER=oltp_username
      - POSTGRES_PASSWORD=Strong123Password
      - POSTGRES_DB=dbname
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Backend.dockerfile
      target: source
    env_file:
      - ./pkg-svcs/backend/.env
    environment:
      - API_HOST=0.0.0.0
      - PG_HOST=postgresql
      - APP_VERSION=1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    volumes:
      - ./pkg-svcs/backend:/app/backend
    command: "npm run startcontainer"
  
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Frontend.dockerfile
      target: source
    env_file:
      - ./pkg-svcs/frontend/.env
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - postgresql
    volumes:
      - ./pkg-svcs/frontend:/app/frontend
    command: "npm run startcontainer"

volumes:
  postgresql:
    external: false
