apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: heiderhengstmann/otlp-blueprint:collector_1.0
          volumeMounts:
            - name: collector-config
              mountPath: /etc/collector-config.yaml
      volumes:
        - name: collector-config
          configMap:
            name: collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: test
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
        protocols:
          grpc:
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - http://*.svc.cluster.local
                - https://*.svc.cluster.local
    exporters:
      jaeger:
        endpoint: "jaeger.test.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9464"
    processors:
      batch:
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
    extensions:
      health_check:
---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
    - name: port-9464
      protocol: TCP
      port: 9464
    - name: port-55680
      protocol: TCP
      port: 55680
    - name: port-55681
      protocol: TCP
      port: 55681
    - name: port-13133
      protocol: TCP
      port: 13133
    - name: port-4317
      protocol: TCP
      port: 4317
    - name: port-4318
      protocol: TCP
      port: 4318
  type: ClusterIP
