apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ${NAMESPACE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: heiderhengstmann/otlp-blueprint:backend_1.8
          env:
            - name: APP_VERSION
              value: 1.0.0
            - name: PG_INFO
              value: '{"database": "tododb", "username": "otlpuser", "password": "otlppassword", "host": "postgresql.${NAMESPACE_NAME}.svc.cluster.local", "port": 5432}'
            - name: OTLP_COLLECTOR_URL
              value: 'http://main-collector.${NAMESPACE_NAME}.svc.cluster.local:4318'
            - name: OTLP_SERVICE_NAME
              value: 'main-collector'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ${NAMESPACE_NAME}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP
