apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: heiderhengstmann/otlp-blueprint:backend_1.0
          env:
            - name: APP_VERSION
              value: 1.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-volume
              mountPath: /app/backend
      volumes:
        - name: backend-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP
