apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: ${NAMESPACE_NAME}
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors: []

    exporters:
      loadbalancing:
        balancer_name: my-loadbalancer
        exporters:
          - otlp:
              endpoint: main-collector.${NAMESPACE_NAME}.svc.cluster.local:4317
              tls:
                insecure: true

    service:
      extensions: []
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [loadbalancing]
