apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ${NAMESPACE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: IfNotPresent
          image: ghcr.io/llprojects/otlp-blueprint/otlp-blueprint-frontend:20230717234527
          env:
            - name: APP_VERSION
              value: 1.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: frontend-volume
              mountPath: /app/frontend
      volumes:
        - name: frontend-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ${NAMESPACE_NAME}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
