apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.43.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
        - name: nginxprometheus
          image: nginx:latest
          ports:
            - containerPort: 9090
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    # Place your Prometheus configuration here
    global:
      scrape_interval: 15s # Default is every 1 minute.

    scrape_configs:
      - job_name: 'collector'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        static_configs:
          - targets: ['main-collector-monitoring.${NAMESPACE_NAME}.svc.cluster.local:8888']

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
  #type: LoadBalancer
