# name: 'OTLP Infrastructure Deployment'
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'infrastructure/**'
# env:
#   tf_version: 'latest'
#   tg_version: 'latest'
#   tf_working_dir: 'infrastructure/terragrunt/dev'
# jobs:
#   tfsec:
#     name: 'tfsec validation'
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@master
#       - name: 'tfsec'
#         uses: tfsec/tfsec-pr-commenter-action@main
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}